In [2]:
import requests
import re
import pandas as pd
from bs4 import BeautifulSoup
import math

In [3]:
url1 = "https://www.disastercenter.com/crime/nycrime.htm"
url2 = "https://www1.nyc.gov/site/nypd/news/p00039/nypd-citywide-crime-statistics-february-2022"
url3 = "https://ucr.fbi.gov/crime-in-the-u.s/2018/crime-in-the-u.s.-2018/tables/table-8/table-8-state-cuts/new-york.xls"

In [4]:
html1 = requests.get(url1)
html2 = requests.get(url2)
html3 = requests.get(url3)

In [5]:
html1_text = html1.text
page1 = BeautifulSoup(html1_text, "html.parser")
html2_text = html2.text
page2 = BeautifulSoup(html2_text, "html.parser")
html3_text = html3.text
page3 = BeautifulSoup(html3_text, "html.parser")

In [6]:
table = page1.find("table")

In [7]:
s = []
temp = table.find("tbody").find("tbody")

temp1 = temp.findAll("tbody")
rows = temp1[2].findAll("tr")
rows[1]

<tr>
<td><font size="-1">Year </font></td>
<td><font size="-1">Population </font></td>
<td><font size="-1">Index </font></td>
<td><font size="-1">Violent </font></td>
<td><font size="-1">Property </font></td>
<td><font size="-1">Murder </font></td>
<td><font size="-1">Rape </font></td>
<td><font size="-1">Robbery </font></td>
<td><font size="-1">assault </font></td>
<td><font size="-1">Burglary </font></td>
<td><font size="-1">Theft </font></td>
<td><font size="-1">Theft </font></td>
</tr>

In [8]:
s = [row.findAll("td") for row in rows]
for item in s:
    for j in range(len(item)):
        item[j] = item[j].text
        item[j] = item[j].replace("\xa0", "")
        item[j] = item[j].replace("\n", "")
        item[j] = item[j].replace(" ", "")
s

[['',
  '',
  '',
  '',
  '',
  '',
  'Forcible',
  '',
  'Aggravated',
  '',
  'Larceny-',
  'Vehicle'],
 ['Year',
  'Population',
  'Index',
  'Violent',
  'Property',
  'Murder',
  'Rape',
  'Robbery',
  'assault',
  'Burglary',
  'Theft',
  'Theft'],
 ['1965',
  '18,073,000',
  '554,050',
  '58,802',
  '495,248',
  '836',
  '2,320',
  '28,182',
  '27,464',
  '183,443',
  '253,353',
  '58,452'],
 ['1966',
  '18,258,000',
  '609,465',
  '62,561',
  '546,904',
  '882',
  '2,439',
  '30,098',
  '29,142',
  '196,127',
  '286,409',
  '64,368'],
 ['1967',
  '18,336,000',
  '692,528',
  '75,124',
  '617,404',
  '996',
  '2,665',
  '40,202',
  '31,261',
  '219,157',
  '314,472',
  '83,775'],
 ['1968',
  '18,113,000',
  '829,453',
  '98,515',
  '730,938',
  '1,185',
  '2,527',
  '59,857',
  '34,946',
  '250,918',
  '375,143',
  '104,877'],
 ['1969',
  '18,321,000',
  '837,210',
  '105,870',
  '731,340',
  '1,324',
  '2,902',
  '64,754',
  '36,890',
  '248,477',
  '367,463',
  '115,400'],
 ['',
  '',
  '',
  '',
  '',
  '',
  'Forcible',
  '',
  'Aggravated',
  '',
  'Larceny-',
  'Vehicle'],
 ['Year',
  'Population',
  'Index',
  'Violent',
  'Property',
  'Murder',
  'Rape',
  'Robbery',
  'assault',
  'Burglary',
  'Theft',
  'Theft'],
 ['1970',
  '18,190,740',
  '904,314',
  '124,613',
  '779,701',
  '1,444',
  '2,875',
  '81,149',
  '39,145',
  '267,474',
  '386,553',
  '125,674'],
 ['1971',
  '18,391,000',
  '935,022',
  '145,048',
  '789,974',
  '1,823',
  '3,225',
  '97,682',
  '42,318',
  '273,704',
  '388,612',
  '127,658'],
 ['1972',
  '18,366,000',
  '804,605',
  '138,542',
  '666,063',
  '2,026',
  '4,199',
  '86,391',
  '45,926',
  '239,886',
  '321,096',
  '105,081'],
 ['1973',
  '18,265,000',
  '814,349',
  '135,468',
  '678,881',
  '2,040',
  '4,852',
  '80,795',
  '47,781',
  '246,246',
  '320,307',
  '112,328'],
 ['1974',
  '18,111,000',
  '911,703',
  '145,427',
  '766,276',
  '1,919',
  '5,240',
  '86,814',
  '51,454',
  '271,824',
  '390,357',
  '104,095'],
 ['1975',
  '18,120,000',
  '1,021,197',
  '155,187',
  '866,010',
  '1,996',
  '5,099',
  '93,499',
  '54,593',
  '301,996',
  '447,740',
  '116,274'],
 ['1976',
  '18,084,000',
  '1,125,739',
  '156,988',
  '968,751',
  '1,969',
  '4,663',
  '95,718',
  '54,638',
  '318,919',
  '516,328',
  '133,504'],
 ['1977',
  '17,924,000',
  '1,091,144',
  '149,087',
  '942,057',
  '1,919',
  '5,272',
  '84,703',
  '57,193',
  '309,735',
  '498,653',
  '133,669'],
 ['1978',
  '17,748,000',
  '1,027,993',
  '149,257',
  '878,736',
  '1,820',
  '5,168',
  '83,785',
  '58,484',
  '292,956',
  '466,516',
  '119,264'],
 ['1979',
  '17,649,000',
  '1,095,140',
  '161,906',
  '933,234',
  '2,092',
  '5,394',
  '93,471',
  '60,949',
  '308,302',
  '500,589',
  '124,343'],
 ['',
  '',
  '',
  '',
  '',
  '',
  'Forcible',
  '',
  'Aggravated',
  '',
  'Larceny-',
  'Vehicle'],
 ['Year',
  'Population',
  'Index',
  'Violent',
  'Property',
  'Murder',
  'Rape',
  'Robbery',
  'assault',
  'Burglary',
  'Theft',
  'Theft'],
 ['1980',
  '17,506,690',
  '1,209,984',
  '180,235',
  '1,029,749',
  '2,228',
  '5,405',
  '112,273',
  '60,329',
  '360,925',
  '535,783',
  '133,041'],
 ['1981',
  '17,594,000',
  '1,214,935',
  '188,178',
  '1,026,757',
  '2,166',
  '5,479',
  '120,344',
  '60,189',
  '350,422',
  '539,486',
  '136,849'],
 ['1982',
  '17,659,000',
  '1,142,202',
  '174,833',
  '967,369',
  '2,013',
  '5,159',
  '107,843',
  '59,818',
  '295,245',
  '534,244',
  '137,880'],
 ['1983',
  '17,667,000',
  '1,042,811',
  '161,489',
  '881,322',
  '1,958',
  '5,296',
  '94,783',
  '59,452',
  '249,115',
  '504,346',
  '127,861'],
 ['1984',
  '17,735,000',
  '989,126',
  '162,157',
  '826,969',
  '1,786',
  '5,599',
  '89,900',
  '64,872',
  '222,956',
  '488,621',
  '115,392'],
 ['1985',
  '17,783,000',
  '993,811',
  '165,365',
  '828,446',
  '1,683',
  '5,706',
  '89,706',
  '68,270',
  '219,633',
  '502,276',
  '106,537'],
 ['1986',
  '17,772,000',
  '1,025,037',
  '175,210',
  '849,827',
  '1,907',
  '5,415',
  '91,360',
  '76,528',
  '217,010',
  '519,570',
  '113,247'],
 ['1987',
  '17,825,000',
  '1,061,021',
  '179,691',
  '881,330',
  '2,016',
  '5,537',
  '89,721',
  '82,417',
  '216,826',
  '539,175',
  '125,329'],
 ['1988',
  '17,898,000',
  '1,129,241',
  '196,396',
  '932,845',
  '2,244',
  '5,479',
  '97,434',
  '91,239',
  '218,060',
  '560,887',
  '153,898'],
 ['1989',
  '17,950,000',
  '1,129,638',
  '203,042',
  '926,596',
  '2,246',
  '5,242',
  '103,983',
  '91,571',
  '211,130',
  '544,459',
  '171,007'],
 ['',
  '',
  '',
  '',
  '',
  '',
  'Forcible',
  '',
  'Aggravated',
  '',
  'Larceny-',
  'Vehicle'],
 ['Year',
  'Population',
  'Index',
  'Violent',
  'Property',
  'Murder',
  'Rape',
  'Robbery',
  'assault',
  'Burglary',
  'Theft',
  'Theft'],
 ['1990',
  '17,990,455',
  '1,144,874',
  '212,458',
  '932,416',
  '2,605',
  '5,368',
  '112,380',
  '92,105',
  '208,813',
  '536,012',
  '187,591'],
 ['1991',
  '18,058,000',
  '1,127,651',
  '210,184',
  '917,467',
  '2,571',
  '5,085',
  '112,342',
  '90,186',
  '204,499',
  '531,681',
  '181,287'],
 ['1992',
  '18,119,000',
  '1,061,489',
  '203,311',
  '858,178',
  '2,397',
  '5,152',
  '108,154',
  '87,608',
  '193,548',
  '495,708',
  '168,922'],
 ['1993',
  '18,197,000',
  '1,010,176',
  '195,352',
  '814,824',
  '2,420',
  '5,008',
  '102,122',
  '85,802',
  '181,709',
  '481,166',
  '151,949'],
 ['1994',
  '18,169,000',
  '921,278',
  '175,433',
  '745,845',
  '2,016',
  '4,700',
  '86,617',
  '82,100',
  '164,650',
  '452,322',
  '128,873'],
 ['1995',
  '18,136,000',
  '827,025',
  '152,683',
  '674,342',
  '1,550',
  '4,290',
  '72,492',
  '74,351',
  '146,562',
  '425,184',
  '102,596'],
 ['1996',
  '18,185,000',
  '751,456',
  '132,206',
  '619,250',
  '1,353',
  '4,174',
  '61,822',
  '64,857',
  '129,828',
  '399,522',
  '89,900'],
 ['1997',
  '18,137,000',
  '709,328',
  '124,890',
  '584,438',
  '1,093',
  '4,075',
  '56,094',
  '63,628',
  '118,306',
  '386,435',
  '79,697'],
 ['1998',
  '18,175,000',
  '652,202',
  '115,915',
  '536,287',
  '924',
  '3,843',
  '49,125',
  '62,023',
  '104,821',
  '363,295',
  '68,171'],
 ['1999',
  '18,196,601',
  '596,743',
  '107,147',
  '489,596',
  '903',
  '3,563',
  '43,821',
  '58,860',
  '93,217',
  '338,118',
  '58,261'],
 ['',
  '',
  '',
  '',
  '',
  '',
  'Forcible',
  '',
  'Aggravated',
  '',
  'Larceny-',
  'Vehicle'],
 ['Year',
  'Population',
  'Index',
  'Violent',
  'Property',
  'Murder',
  'Rape',
  'Robbery',
  'assault',
  'Burglary',
  'Theft',
  'Theft'],
 ['2000',
  '18,976,457',
  '588,189',
  '124,890',
  '483,078',
  '952',
  '3,530',
  '40,539',
  '60,090',
  '87,946',
  '340,901',
  '54,231'],
 ['2001',
  '19,084,350',
  '556,025',
  '98,022',
  '458,003',
  '960',
  '3,546',
  '36,555',
  '56,961',
  '80,400',
  '329,316',
  '48,287'],
 ['2002',
  '19,134,293',
  '537,121',
  '95,030',
  '442,091',
  '909',
  '3,885',
  '36,653',
  '53,583',
  '76,700',
  '318,025',
  '47,366'],
 ['2003',
  '19,212,425',
  '521,565',
  '89,486',
  '432,079',
  '934',
  '3,775',
  '35,790',
  '48,987',
  '75,453',
  '311,422',
  '45,204'],
 ['2004',
  '19,280,727',
  '507,648',
  '84,914',
  '422,734',
  '889',
  '3,608',
  '33,506',
  '46,911',
  '70,696',
  '311,036',
  '41,002'],
 ['2005',
  '19,315,721',
  '491,829',
  '85,839',
  '405,990',
  '874',
  '3,636',
  '35,179',
  '46,150',
  '68,034',
  '302,220',
  '35,736'],
 ['2006',
  '19,306,183',
  '482,270',
  '83,966',
  '396,304',
  '921',
  '3,169',
  '34,489',
  '45,387',
  '68,565',
  '295,605',
  '32,134'],
 ['2007',
  '19,297,729',
  '461,731',
  '79,915',
  '381,816',
  '801',
  '2,926',
  '31,094',
  '45,094',
  '64,857',
  '288,929',
  '28,030'],
 ['2008',
  '19,467,789',
  '466,131',
  '77,546',
  '388,585',
  '836',
  '2,799',
  '31,789',
  '42,122',
  '65,537',
  '297,952',
  '25,096'],
 ['2009',
  '19,541,453',
  '452,647',
  '75,110',
  '377,537',
  '781',
  '2,582',
  '28,141',
  '43,606',
  '62,769',
  '292,897',
  '21,871'],
 ['',
  '',
  '',
  '',
  '',
  '',
  'Forcible',
  '',
  'Aggravated',
  '',
  'Larceny-',
  'Vehicle'],
 ['Year',
  'Population',
  'Index',
  'Violent',
  'Property',
  'Murder',
  'Rape',
  'Robbery',
  'assault',
  'Burglary',
  'Theft',
  'Theft'],
 ['2010',
  '19,395,206',
  '456,202',
  '76,492',
  '379,710',
  '868',
  '2,797',
  '28,630',
  '44,197',
  '65,839',
  '293,232',
  '20,639'],
 ['2011',
  '19,501,616',
  '449,300',
  '77,463',
  '371,837',
  '769',
  '2,751',
  '28,405',
  '45,538',
  '65,227',
  '287,361',
  '19,249'],
 ['2012',
  '19,576,125',
  '454,803',
  '79,535',
  '375,268',
  '683',
  '2,837',
  '28,633',
  '47,382',
  '64,389',
  '293,562',
  '17,317'],
 ['2013',
  '19,695,680',
  '436,166',
  '77,563',
  '358,603',
  '644',
  '2,575',
  '27,241',
  '46,130',
  '56,444',
  '286,676',
  '15,483'],
 ['2014',
  '19,748,858',
  '415,085',
  '75,972',
  '339,113',
  '616',
  '4,316',
  '24,036',
  '45,295',
  '50,738',
  '272,624',
  '15,751'],
 ['2015',
  '19,747,183',
  '392,351',
  '75,126',
  '317,225',
  '613',
  '4,414',
  '23,879',
  '44,493',
  '44,117',
  '257,837',
  '15,271'],
 ['2016',
  '19,745,289',
  '379,466',
  '74,285',
  '305,181',
  '630',
  '4,569',
  '22,316',
  '45,079',
  '39,821',
  '250,968',
  '14,392'],
 ['2017',
  '19,590,719',
  '364,136',
  '70,746',
  '293,390',
  '550',
  '6,297',
  '20,122',
  '43,777',
  '34,928',
  '245,093',
  '13,369'],
 ['2018',
  '19,530,351',
  '350,055',
  '68,512',
  '281,543',
  '562',
  '6,577',
  '18,191',
  '43,182',
  '31,158',
  '237,243',
  '13,142'],
 ['2019',
  '19,453,561',
  '336,919',
  '69,764',
  '267,155',
  '558',
  '6,583',
  '18,068',
  '44,555',
  '27,600',
  '226,851',
  '12,704']]

In [9]:
Year = []
Population = []
Index = []
Violent = []
Property = []
Murder = []
Forcible_Rape = []
Robbery = []
Aggravated_assault = []
Burglary = []
Larceny_Theft = []
Vehicle_Theft = []

for i in s:
    if i[0] in ["", "Year"]:
        continue
    Year.append(i[0])
    Population.append(i[1])
    Index.append(i[2])
    Violent.append(i[3])
    Property.append(i[4])
    Murder.append(i[5])
    Forcible_Rape.append(i[6])
    Robbery.append(i[7])
    Aggravated_assault.append(i[8])
    Burglary.append(i[9])
    Larceny_Theft.append(i[10])
    Vehicle_Theft.append(i[11])
Year

['1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019']

In [10]:
df = pd.DataFrame(
    {
        "Year": Year,
        "Population": Population,
        "Index": Index,
        "Violent": Violent,
        "Property": Property,
        "Murder": Murder,
        "Forcible_Rape": Forcible_Rape,
        "Robbery": Robbery,
        "Aggravated_assault": Aggravated_assault,
        "Burglary": Burglary,
        "Larceny_Theft": Larceny_Theft,
        "Vehicle_Theft": Vehicle_Theft,
    }
)
df

,Year,Population,Index,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
0,1965,"18,073,000","554,050","58,802","495,248",836,"2,320","28,182","27,464","183,443","253,353","58,452"
1,1966,"18,258,000","609,465","62,561","546,904",882,"2,439","30,098","29,142","196,127","286,409","64,368"
2,1967,"18,336,000","692,528","75,124","617,404",996,"2,665","40,202","31,261","219,157","314,472","83,775"
3,1968,"18,113,000","829,453","98,515","730,938","1,185","2,527","59,857","34,946","250,918","375,143","104,877"
4,1969,"18,321,000","837,210","105,870","731,340","1,324","2,902","64,754","36,890","248,477","367,463","115,400"
5,1970,"18,190,740","904,314","124,613","779,701","1,444","2,875","81,149","39,145","267,474","386,553","125,674"
6,1971,"18,391,000","935,022","145,048","789,974","1,823","3,225","97,682","42,318","273,704","388,612","127,658"
7,1972,"18,366,000","804,605","138,542","666,063","2,026","4,199","86,391","45,926","239,886","321,096","105,081"
8,1973,"18,265,000","814,349","135,468","678,881","2,040","4,852","80,795","47,781","246,246","320,307","112,328"
9,1974,"18,111,000","911,703","145,427","766,276","1,919","5,240","86,814","51,454","271,824","390,357","104,095"
10,1975,"18,120,000","1,021,197","155,187","866,010","1,996","5,099","93,499","54,593","301,996","447,740","116,274"
11,1976,"18,084,000","1,125,739","156,988","968,751","1,969","4,663","95,718","54,638","318,919","516,328","133,504"
12,1977,"17,924,000","1,091,144","149,087","942,057","1,919","5,272","84,703","57,193","309,735","498,653","133,669"
13,1978,"17,748,000","1,027,993","149,257","878,736","1,820","5,168","83,785","58,484","292,956","466,516","119,264"
14,1979,"17,649,000","1,095,140","161,906","933,234","2,092","5,394","93,471","60,949","308,302","500,589","124,343"
15,1980,"17,506,690","1,209,984","180,235","1,029,749","2,228","5,405","112,273","60,329","360,925","535,783","133,041"
16,1981,"17,594,000","1,214,935","188,178","1,026,757","2,166","5,479","120,344","60,189","350,422","539,486","136,849"
17,1982,"17,659,000","1,142,202","174,833","967,369","2,013","5,159","107,843","59,818","295,245","534,244","137,880"
18,1983,"17,667,000","1,042,811","161,489","881,322","1,958","5,296","94,783","59,452","249,115","504,346","127,861"
19,1984,"17,735,000","989,126","162,157","826,969","1,786","5,599","89,900","64,872","222,956","488,621","115,392"
20,1985,"17,783,000","993,811","165,365","828,446","1,683","5,706","89,706","68,270","219,633","502,276","106,537"
21,1986,"17,772,000","1,025,037","175,210","849,827","1,907","5,415","91,360","76,528","217,010","519,570","113,247"
22,1987,"17,825,000","1,061,021","179,691","881,330","2,016","5,537","89,721","82,417","216,826","539,175","125,329"
23,1988,"17,898,000","1,129,241","196,396","932,845","2,244","5,479","97,434","91,239","218,060","560,887","153,898"
24,1989,"17,950,000","1,129,638","203,042","926,596","2,246","5,242","103,983","91,571","211,130","544,459","171,007"
25,1990,"17,990,455","1,144,874","212,458","932,416","2,605","5,368","112,380","92,105","208,813","536,012","187,591"
26,1991,"18,058,000","1,127,651","210,184","917,467","2,571","5,085","112,342","90,186","204,499","531,681","181,287"
27,1992,"18,119,000","1,061,489","203,311","858,178","2,397","5,152","108,154","87,608","193,548","495,708","168,922"
28,1993,"18,197,000","1,010,176","195,352","814,824","2,420","5,008","102,122","85,802","181,709","481,166","151,949"
29,1994,"18,169,000","921,278","175,433","745,845","2,016","4,700","86,617","82,100","164,650","452,322","128,873"
30,1995,"18,136,000","827,025","152,683","674,342","1,550","4,290","72,492","74,351","146,562","425,184","102,596"
31,1996,"18,185,000","751,456","132,206","619,250","1,353","4,174","61,822","64,857","129,828","399,522","89,900"
32,1997,"18,137,000","709,328","124,890","584,438","1,093","4,075","56,094","63,628","118,306","386,435","79,697"
33,1998,"18,175,000","652,202","115,915","536,287",924,"3,843","49,125","62,023","104,821","363,295","68,171"
34,1999,"18,196,601","596,743","107,147","489,596",903,"3,563","43,821","58,860","93,217","338,118","58,261"
35,2000,"18,976,457","588,189","124,890","483,078",952,"3,530","40,539","60,090","87,946","340,901","54,231"
36,2001,"19,084,350","556,025","98,022","458,003",960,"3,546","36,555","56,961","80,400","329,316","48,287"
37,2002,"19,134,293","537,121","95,030","442,091",909,"3,885","36,653","53,583","76,700","318,025","47,366"
38,2003,"19,212,425","521,565","89,486","432,079",934,"3,775","35,790","48,987","75,453","311,422","45,204"
39,2004,"19,280,727","507,648","84,914","422,734",889,"3,608","33,506","46,911","70,696","311,036","41,002"
40,2005,"19,315,721","491,829","85,839","405,990",874,"3,636","35,179","46,150","68,034","302,220","35,736"
41,2006,"19,306,183","482,270","83,966","396,304",921,"3,169","34,489","45,387","68,565","295,605","32,134"
42,2007,"19,297,729","461,731","79,915","381,816",801,"2,926","31,094","45,094","64,857","288,929","28,030"
43,2008,"19,467,789","466,131","77,546","388,585",836,"2,799","31,789","42,122","65,537","297,952","25,096"
44,2009,"19,541,453","452,647","75,110","377,537",781,"2,582","28,141","43,606","62,769","292,897","21,871"
45,2010,"19,395,206","456,202","76,492","379,710",868,"2,797","28,630","44,197","65,839","293,232","20,639"
46,2011,"19,501,616","449,300","77,463","371,837",769,"2,751","28,405","45,538","65,227","287,361","19,249"
47,2012,"19,576,125","454,803","79,535","375,268",683,"2,837","28,633","47,382","64,389","293,562","17,317"
48,2013,"19,695,680","436,166","77,563","358,603",644,"2,575","27,241","46,130","56,444","286,676","15,483"
49,2014,"19,748,858","415,085","75,972","339,113",616,"4,316","24,036","45,295","50,738","272,624","15,751"
50,2015,"19,747,183","392,351","75,126","317,225",613,"4,414","23,879","44,493","44,117","257,837","15,271"
51,2016,"19,745,289","379,466","74,285","305,181",630,"4,569","22,316","45,079","39,821","250,968","14,392"
52,2017,"19,590,719","364,136","70,746","293,390",550,"6,297","20,122","43,777","34,928","245,093","13,369"
53,2018,"19,530,351","350,055","68,512","281,543",562,"6,577","18,191","43,182","31,158","237,243","13,142"
54,2019,"19,453,561","336,919","69,764","267,155",558,"6,583","18,068","44,555","27,600","226,851","12,704"